// Pure logic for a Sudoku puzzle. A puzzle is generated by scrambling a known
// valid solution with transformations that preserve Sudoku validity (digit
// relabeling, row/column swaps within bands, band/stack swaps, transpose), then
// blanking cells. Because we keep the full solution alongside the puzzle, the
// UI validates entries against it directly — no solver needed at runtime.

export type Grid = number[] // length 81, 0 = empty

export const SIZE = 9
export const CELLS = 81

// A single valid completed Sudoku used as the seed for all scrambling.
const BASE_SOLUTION: Grid = [
  5, 3, 4, 6, 7, 8, 9, 1, 2,
  6, 7, 2, 1, 9, 5, 3, 4, 8,
  1, 9, 8, 3, 4, 2, 5, 6, 7,
  8, 5, 9, 7, 6, 1, 4, 2, 3,
  4, 2, 6, 8, 5, 3, 7, 9, 1,
  7, 1, 3, 9, 2, 4, 8, 5, 6,
  9, 6, 1, 5, 3, 7, 2, 8, 4,
  2, 8, 7, 4, 1, 9, 6, 3, 5,
  3, 4, 5, 2, 8, 6, 1, 7, 9,
]

// mulberry32: a tiny, fast, deterministic PRNG so a given seed always yields the
// same puzzle (used for the "daily" puzzle).
function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function shuffle<T>(items: T[], rng: () => number): T[] {
  const out = [...items]
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

function toMatrix(grid: Grid): number[][] {
  const rows: number[][] = []
  for (let r = 0; r < SIZE; r += 1) rows.push(grid.slice(r * SIZE, r * SIZE + SIZE))
  return rows
}

function toFlat(matrix: number[][]): Grid {
  return matrix.flat()
}

// A permutation of the row (or column) indices 0..8 that keeps each band of
// three together: bands are shuffled among themselves, and the three lines
// inside each band are shuffled among themselves.
function bandedOrder(rng: () => number): number[] {
  const bands = shuffle([0, 1, 2], rng)
  const order: number[] = []
  for (const band of bands) {
    for (const line of shuffle([0, 1, 2], rng)) order.push(band * 3 + line)
  }
  return order
}

export function scrambledSolution(seed: number): Grid {
  const rng = mulberry32(seed)

  // Relabel digits 1..9 by a random permutation.
  const digits = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9], rng)
  let matrix = toMatrix(BASE_SOLUTION.map((v) => digits[v - 1]))

  // Reorder rows and columns within their bands/stacks.
  const rowOrder = bandedOrder(rng)
  const colOrder = bandedOrder(rng)
  matrix = rowOrder.map((r) => colOrder.map((c) => matrix[r][c]))

  // Optionally transpose (swap rows and columns) for extra variety.
  if (rng() < 0.5) {
    const transposed: number[][] = Array.from({ length: SIZE }, () => new Array(SIZE).fill(0))
    for (let r = 0; r < SIZE; r += 1) {
      for (let c = 0; c < SIZE; c += 1) transposed[c][r] = matrix[r][c]
    }
    matrix = transposed
  }

  return toFlat(matrix)
}

export type Puzzle = {
  puzzle: Grid // the board shown to the player (0 = empty)
  solution: Grid // the completed board
  givens: boolean[] // which cells are fixed clues (not editable)
}

// Blanks `holes` cells from a scrambled solution. Uniqueness of the solution is
// not required: the reference solution is kept, so correctness is checked
// against it directly.
export function generatePuzzle(seed: number, holes = 45): Puzzle {
  const solution = scrambledSolution(seed)
  const rng = mulberry32(seed ^ 0x9e3779b9)
  const indices = shuffle(
    Array.from({ length: CELLS }, (_, i) => i),
    rng,
  )
  const clamped = Math.max(0, Math.min(CELLS, holes))
  const blanked = new Set(indices.slice(0, clamped))
  const puzzle = solution.map((value, index) => (blanked.has(index) ? 0 : value))
  const givens = puzzle.map((value) => value !== 0)
  return { puzzle, solution, givens }
}

export function rowOf(index: number): number {
  return Math.floor(index / SIZE)
}
export function colOf(index: number): number {
  return index % SIZE
}
export function boxOf(index: number): number {
  return Math.floor(rowOf(index) / 3) * 3 + Math.floor(colOf(index) / 3)
}

// Indices whose value duplicates another filled cell in the same row, column or
// 3×3 box. Empty cells (0) never conflict.
export function findConflicts(grid: Grid): Set<number> {
  const conflicts = new Set<number>()
  const groups: ((index: number) => number)[] = [rowOf, colOf, boxOf]
  for (const groupOf of groups) {
    const seen = new Map<string, number[]>()
    for (let i = 0; i < grid.length; i += 1) {
      const value = grid[i]
      if (!value) continue
      const key = `${groupOf(i)}:${value}`
      const list = seen.get(key)
      if (list) list.push(i)
      else seen.set(key, [i])
    }
    for (const list of seen.values()) {
      if (list.length > 1) for (const i of list) conflicts.add(i)
    }
  }
  return conflicts
}

export function isComplete(grid: Grid): boolean {
  return grid.every((value) => value >= 1 && value <= 9) && findConflicts(grid).size === 0
}

export function isSolved(grid: Grid, solution: Grid): boolean {
  return grid.length === solution.length && grid.every((value, index) => value === solution[index])
}

// Seed derived from the calendar day, so everyone shares the daily puzzle.
export function dailySeed(date: Date = new Date()): number {
  return Math.floor(date.getTime() / 86_400_000)
}

// Difficulty is expressed as how many cells are blanked out of 81. More holes
// means fewer clues, hence a harder board.
export type Difficulty = "facil" | "medio" | "dificil"

export const DIFFICULTIES: { id: Difficulty; label: string; holes: number }[] = [
  { id: "facil", label: "Fácil", holes: 35 },
  { id: "medio", label: "Médio", holes: 45 },
  { id: "dificil", label: "Difícil", holes: 52 },
]

export function holesFor(difficulty: Difficulty): number {
  return DIFFICULTIES.find((d) => d.id === difficulty)?.holes ?? 45
}
