// Pure logic for a Sudoku puzzle. A puzzle is generated by scrambling a known
// valid solution with transformations that preserve Sudoku validity (digit
// relabeling, row/column swaps within bands, band/stack swaps, transpose), then
// blanking cells one at a time, keeping a blank only while the board still has
// exactly one solution.
//
// That last condition is what makes it a Sudoku rather than a grid to fill in.
// Blanking cells at random used to leave ambiguous boards — measured over 200
// generated boards per level, 31% of "fácil", 80% of "médio" and 100% of
// "difícil" had more than one valid completion, so a player could complete the
// grid correctly and be told they had not.

export type Grid = number[] // length 81, 0 = empty

export const SIZE = 9
export const CELLS = 81

// A single valid completed Sudoku used as the seed for all scrambling.
const BASE_SOLUTION: Grid = [
  5, 3, 4, 6, 7, 8, 9, 1, 2,
  6, 7, 2, 1, 9, 5, 3, 4, 8,
  1, 9, 8, 3, 4, 2, 5, 6, 7,
  8, 5, 9, 7, 6, 1, 4, 2, 3,
  4, 2, 6, 8, 5, 3, 7, 9, 1,
  7, 1, 3, 9, 2, 4, 8, 5, 6,
  9, 6, 1, 5, 3, 7, 2, 8, 4,
  2, 8, 7, 4, 1, 9, 6, 3, 5,
  3, 4, 5, 2, 8, 6, 1, 7, 9,
]

// mulberry32: a tiny, fast, deterministic PRNG so a given seed always yields the
// same puzzle (used for the "daily" puzzle).
function mulberry32(seed: number): () => number {
  let a = seed >>> 0
  return () => {
    a |= 0
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

function shuffle<T>(items: T[], rng: () => number): T[] {
  const out = [...items]
  for (let i = out.length - 1; i > 0; i -= 1) {
    const j = Math.floor(rng() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

function toMatrix(grid: Grid): number[][] {
  const rows: number[][] = []
  for (let r = 0; r < SIZE; r += 1) rows.push(grid.slice(r * SIZE, r * SIZE + SIZE))
  return rows
}

function toFlat(matrix: number[][]): Grid {
  return matrix.flat()
}

// A permutation of the row (or column) indices 0..8 that keeps each band of
// three together: bands are shuffled among themselves, and the three lines
// inside each band are shuffled among themselves.
function bandedOrder(rng: () => number): number[] {
  const bands = shuffle([0, 1, 2], rng)
  const order: number[] = []
  for (const band of bands) {
    for (const line of shuffle([0, 1, 2], rng)) order.push(band * 3 + line)
  }
  return order
}

export function scrambledSolution(seed: number): Grid {
  const rng = mulberry32(seed)

  // Relabel digits 1..9 by a random permutation.
  const digits = shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9], rng)
  let matrix = toMatrix(BASE_SOLUTION.map((v) => digits[v - 1]))

  // Reorder rows and columns within their bands/stacks.
  const rowOrder = bandedOrder(rng)
  const colOrder = bandedOrder(rng)
  matrix = rowOrder.map((r) => colOrder.map((c) => matrix[r][c]))

  // Optionally transpose (swap rows and columns) for extra variety.
  if (rng() < 0.5) {
    const transposed: number[][] = Array.from({ length: SIZE }, () => new Array(SIZE).fill(0))
    for (let r = 0; r < SIZE; r += 1) {
      for (let c = 0; c < SIZE; c += 1) transposed[c][r] = matrix[r][c]
    }
    matrix = transposed
  }

  return toFlat(matrix)
}

export type Puzzle = {
  puzzle: Grid // the board shown to the player (0 = empty)
  solution: Grid // the completed board
  givens: boolean[] // which cells are fixed clues (not editable)
}

// Whether `value` may be placed at `index` without repeating in its row,
// column or box. Reads the grid directly so the solver stays allocation-free.
function canPlace(grid: Grid, index: number, value: number): boolean {
  const row = rowOf(index)
  const col = colOf(index)
  const boxRow = Math.floor(row / 3) * 3
  const boxCol = Math.floor(col / 3) * 3
  for (let k = 0; k < SIZE; k += 1) {
    if (grid[row * SIZE + k] === value) return false
    if (grid[k * SIZE + col] === value) return false
    if (grid[(boxRow + Math.floor(k / 3)) * SIZE + boxCol + (k % 3)] === value) return false
  }
  return true
}

// Number of ways the board can be completed, counted up to `cap`. Stopping at
// the cap is what keeps this cheap: telling "one solution" from "more than one"
// never needs the full count. Backtracks from the most constrained empty cell
// first, which prunes hard boards quickly.
//
// Mutates `grid` while searching and restores it before returning.
export function countSolutions(grid: Grid, cap = 2): number {
  // A board that already repeats a digit has no completion, but the search
  // cannot see that: canPlace only checks the cell it is about to fill, so a
  // pre-existing conflict sends it through the whole space to prove a negative.
  // Measured: a grid with two 5s in the first row did not finish in 60s.
  if (findConflicts(grid).size > 0) return 0

  let found = 0

  const search = (): void => {
    let target = -1
    let candidates: number[] | null = null
    for (let i = 0; i < CELLS; i += 1) {
      if (grid[i] !== 0) continue
      const options: number[] = []
      for (let value = 1; value <= SIZE; value += 1) {
        if (canPlace(grid, i, value)) options.push(value)
      }
      // A blank with nowhere to go means this branch is already dead.
      if (options.length === 0) return
      if (!candidates || options.length < candidates.length) {
        target = i
        candidates = options
      }
      // Nothing beats a forced cell, so stop looking for a better one.
      if (options.length === 1) break
    }

    // No blanks left: the board is complete, so this is one solution.
    if (target === -1 || !candidates) {
      found += 1
      return
    }

    for (const value of candidates) {
      grid[target] = value
      search()
      grid[target] = 0
      if (found >= cap) return
    }
  }

  search()
  return found
}

export function hasUniqueSolution(grid: Grid): boolean {
  return countSolutions(grid, 2) === 1
}

// Blanks up to `holes` cells from a scrambled solution, keeping each blank only
// while the board still has exactly one solution. The reference solution is
// kept for hinting, but it is not what a win is checked against — any valid
// completion is correct, and with a unique solution there is only one.
//
// Cells are tried in a seeded random order, so a given seed always produces the
// same puzzle. If a blank would make the board ambiguous the value is put back
// and the next cell is tried; `holes` is therefore a target, and the returned
// board may have slightly fewer.
export function generatePuzzle(seed: number, holes = 45): Puzzle {
  const solution = scrambledSolution(seed)
  const rng = mulberry32(seed ^ 0x9e3779b9)
  const order = shuffle(
    Array.from({ length: CELLS }, (_, i) => i),
    rng,
  )
  const target = Math.max(0, Math.min(CELLS, holes))

  const puzzle = [...solution]
  let blanked = 0
  for (const index of order) {
    if (blanked >= target) break
    const value = puzzle[index]
    puzzle[index] = 0
    if (hasUniqueSolution(puzzle)) blanked += 1
    else puzzle[index] = value
  }

  const givens = puzzle.map((value) => value !== 0)
  return { puzzle, solution, givens }
}

export function rowOf(index: number): number {
  return Math.floor(index / SIZE)
}
export function colOf(index: number): number {
  return index % SIZE
}
export function boxOf(index: number): number {
  return Math.floor(rowOf(index) / 3) * 3 + Math.floor(colOf(index) / 3)
}

// Indices whose value duplicates another filled cell in the same row, column or
// 3×3 box. Empty cells (0) never conflict.
export function findConflicts(grid: Grid): Set<number> {
  const conflicts = new Set<number>()
  const groups: ((index: number) => number)[] = [rowOf, colOf, boxOf]
  for (const groupOf of groups) {
    const seen = new Map<string, number[]>()
    for (let i = 0; i < grid.length; i += 1) {
      const value = grid[i]
      if (!value) continue
      const key = `${groupOf(i)}:${value}`
      const list = seen.get(key)
      if (list) list.push(i)
      else seen.set(key, [i])
    }
    for (const list of seen.values()) {
      if (list.length > 1) for (const i of list) conflicts.add(i)
    }
  }
  return conflicts
}

// A finished, correct board: every cell filled with 1–9 and no repeats in any
// row, column or box. This — not equality with the generated solution — is what
// winning means, so a player who reaches a valid board by another route still
// wins. Puzzles are generated with a unique solution, so in practice the two
// agree; this is the definition that stays right if that ever changes.
export function isComplete(grid: Grid): boolean {
  if (grid.length !== CELLS) return false
  return grid.every((value) => value >= 1 && value <= SIZE) && findConflicts(grid).size === 0
}

export function isSolved(grid: Grid, solution: Grid): boolean {
  return grid.length === solution.length && grid.every((value, index) => value === solution[index])
}

// Difficulty is expressed as how many cells are blanked out of 81. More holes
// means fewer clues, hence a harder board.
export type Difficulty = "facil" | "medio" | "dificil"

export const DIFFICULTIES: { id: Difficulty; label: string; holes: number }[] = [
  { id: "facil", label: "Fácil", holes: 35 },
  { id: "medio", label: "Médio", holes: 45 },
  { id: "dificil", label: "Difícil", holes: 52 },
]

export function holesFor(difficulty: Difficulty): number {
  return DIFFICULTIES.find((d) => d.id === difficulty)?.holes ?? 45
}
